name: 'Install SteamCMD'
description: 'Set up the current release of SteamCMD and add it to the PATH.'
branding:
  icon: 'terminal'
  color: 'gray-dark'
outputs:
  directory:
    description: 'SteamCMD installation directory.'
  executable:
    description: 'Path to `steamcmd.sh` or `steamcmd.exe` file, depending on OS.'
runs:
  using: 'node20'
  main: 'dist/index.js'
