name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: Test 'Setup SteamCMD'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup SteamCMD
        id: setup-steamcmd
        uses: ./

      - name: Login to Steam anonymously
        run: steamcmd +login anonymous +quit
        # PowerShell (default on Windows) hides some error messages
        shell: bash

      - name: Print outputs
        run: |
          echo ${{ steps.setup-steamcmd.outputs.directory }}
          echo ${{ steps.setup-steamcmd.outputs.executable }}
